config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, except: [:index, :destroy]
  resources :projects, except: [:index]

  get '/', to: "welcome#home"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  post '/logout', to: "sessions#destroy"
  patch '/projects/:id/support', to: "projects#support"
  get '/search', to: "welcome#home"
  get '/notes/:id', to: "users#notes", as: "note"
  patch '/notes/:id', to: "users#notes_save"
  get '/category/:id', to: "welcome#category", as: "category"
  get '/stats/:id', to: "users#stats", as: "stat"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :projects
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_backings, :foreign_key => :backed_project_id
  has_many :backers, through: :project_backings, :source => :project_backer
  belongs_to :creator, :class_name => "User"
  belongs_to :category
  mount_uploader :project_photo, ProjectPhotoUploader

  ###validations
  validates :title, presence: true
  validates :description, presence: true, length: {minimum: 30}
  validates :funds_needed, presence: true

  def number_of_supporters
    self.backers.uniq.count
  end

  def lowercase_title
    self.title.downcase
  end

  def self.search(q)
    if q
      where('title LIKE ?', "%#{q}%")
    else
      all
    end
  end

end

app/models/project_backing.rb
class ProjectBacking < ApplicationRecord
  belongs_to :project_backer, :class_name => "User"
  belongs_to :backed_project, :class_name => "Project" 

end

app/models/user.rb
class User < ApplicationRecord
  ###associations
  has_many :project_backings, :foreign_key => :project_backer_id
  has_many :backed_projects, through: :project_backings
  has_many :created_projects, :foreign_key => :creator_id, :class_name => "Project"

  ###validations
  validates :username, uniqueness: true, presence: true
  validates :password, presence: true, :on => :create
  validates :password_confirmation, presence: true, :on => :create


  has_secure_password


  def full_name
    "#{first_name} #{last_name}"
  end

  def total_projects
    self.created_projects.count
  end

  def goal_reached_projects
    self.created_projects.select do |project|
      project.funds_acquired >= project.funds_needed
    end
  end


  def total_funds_acquired
    array = self.created_projects.map do |project|
      project.funds_acquired
    end
    array.inject(0){|sum,x| sum + x }
  end

  def total_funds_needed
    array = self.created_projects.map do |project|
      project.funds_needed
    end
    array.inject(0){|sum,x| sum + x }
  end

  def most_popular_project
    array = self.created_projects.max_by do |project|
      project.backers.count
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user
  helper_method :current_user, :logged_in?, :require_logged_in

  def current_user
    @user = (User.find_by(id: session[:user_id]) || User.new)
  end

  def logged_in?
    current_user.id != nil
  end

  def require_logged_in
    return redirect_to(controller: 'sessions', action: 'new') unless logged_in?
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_logged_in, except: [:show]
  before_action :find_project, only: [:show, :support, :edit, :update, :destroy]


  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.creator_id = current_user.id
    @project.save
    if @project.valid?
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def show
  end

  def support
    @project.funds_acquired += params[:project][:funds_acquired].to_i
    @project.update(funds_acquired: @project.funds_acquired)
    @project.backers << current_user
    redirect_to project_path(@project)
  end

  def edit
  end

  def update
    @project.update(project_params)
    redirect_to project_path(@project)
  end

  def destroy
    @project.destroy
    redirect_to user_path(current_user.id)
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, :funds_needed, :funds_acquired, :number_of_supporters, :creator_id, :category_id, :project_photo, :q)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:user][:username])
    user = user.try(:authenticate, params[:user][:password])
    if !user
      flash[:notice] = "No user found with that username or password"
      render :new
    else
      session[:user_id] = user.id
      @user = user
      redirect_to '/'
    end
  end

  def destroy
    session.delete :user_id
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.valid?
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def notes
    @user = User.find(params[:id])
  end

  def notes_save
    @user = User.find(params[:id])
    @user.update(note_content: params[:user][:note_content])
    redirect_to note_path(@user)
  end

  def stats
    @user = User.find(params[:id])
  end


  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :password, :password_confirmation, :email, :age, :gender, :country, :occupation, :note_content)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
    @categories = Category.all
    flash[:notice] = nil
    @projects = Project.search(params[:q])
    if @projects == []
      flash[:notice] = "Oops, We couldn't find any results"
    end
  end

  def category
    @categories = Category.all
    @category = Category.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bright Ideas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Jquery Script -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.js Script -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <!-- Bootstrap Complete JS-->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <!-- Complete CSS CDN -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"></script>


    <!--Google font -->
    <link href="https://fonts.googleapis.com/css?family=Shadows+Into+Light" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Kodchasan" rel="stylesheet">

  </head>

  <body>
        <div class="header sticky-top" id="myHeader">
          <span> <a href="/">BRIGHT<img src='https://d2v9y0dukr6mq2.cloudfront.net/video/thumbnail/4M04x-Kueijnfl2yb/shining-light-bulb-with-human-brain-big-idea-innovation-concept-hd-graphic-animation_r4g_iae8x_thumbnail-full12.png' width='120' height='80'>IDEAS </a></span>
        <div class="login_logout">
              <% if logged_in? %>
                Welcome, <%= current_user.first_name %><br>
                <%= form_tag '/logout', method: "post" do %>
                <input type=submit value="Logout"><br>
                  <%end%>
              <% else %>
                <%= form_tag '/login', method: "get" do %>
                  <input type=submit value="Login"><br>
                <%end%>
              <% end %>
        </div>
        <div class="mini-header">
          <% if logged_in? %>
          <%= link_to "My Profile", user_path(current_user.id) %>&nbsp | &nbsp<%= link_to "Start a Project", new_project_path %>&nbsp | &nbsp<%= link_to "My Notes", note_path(current_user.id)%>&nbsp | &nbsp<%= link_to "My Stats", stat_path(current_user.id) %>
          <% end %>
        </div>
      </div>
    <%= yield %>
  </body>
</html>

app/views/projects/edit.html.erb
<div class="form">
  <br>
  <h2>Edit project:</h2><br>
  <%= form_for @project do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title %> <br>

      <%= f.label :category_id %>
      <%= f.collection_select :category_id, Category.all, :id, :name %>  <br>

      <%= f.label :description %>
      <%= f.text_area :description, :cols => "75", :rows => "12" %> <br>

      <%= f.label :funds_needed, "Funds needed: $" %>
      <%= f.number_field :funds_needed %> <br>

      <%= f.label :project_photo%>
      <%= f.file_field :project_photo %> <br>

      <%= f.submit %>
    <% end %>

</div>

app/views/projects/new.html.erb
<div class="form">
  <br>
  <h1>Start a project:</h1>

  <div class="error">
  <% if @project.errors.any? %>
    <% @project.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  <% end %>
  </div>

  <%= form_for @project do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title %> <br>

      <%= f.label :category_id %>
      <%= f.collection_select :category_id, Category.all, :id, :name %>  <br>

      <%= f.label :description %>
      <%= f.text_area :description, :cols => "75", :rows => "12"  %> <br>

      <%= f.label :funds_needed, "Funds needed: $" %>
      <%= f.number_field :funds_needed%> <br>

      <%= f.label :project_photo, "Add an image of your project:"%>
      <%= f.file_field :project_photo %> <br>

      <%= f.submit %>
    <% end %>

</div>

app/views/projects/show.html.erb
<div class="show">
  <div class="row">
    <div class="project-info col-sm-8">
    <h1><%= @project.title %></h1>
    <h5>By: <%= link_to @project.creator.full_name, user_path(@project.creator)%></h5><br>
        Category: <%= @project.category.name %>  <br>
        Description: <%= @project.description %> <br><br>
        <% if @project.funds_acquired >= @project.funds_needed %>
          <div class="goal-reached">GOAL REACHED!!! </div>
          <img src="https://d2v9y0dukr6mq2.cloudfront.net/video/thumbnail/uh59Wh0/money-bag-usd-sketch-illustration-hand-drawn-animation-transparent_h3kdngey__F0014.png", width= "150", height= "100">
        <% end %>
          <div class="funds">
            $<%= @project.funds_acquired %> pledged of $<%= @project.funds_needed %> goal. <br>
          </div>
        Number of backers: <%= @project.number_of_supporters %>
    </div>
    <div class="project-picture col-sm-4">
      <%= image_tag(@project.project_photo.url, width: "350", height: "275") unless !@project.project_photo.url %>
    </div>
  </div>


  <div class="back-this-project">
  <% if logged_in? %>
    <%= form_for @project, url: "/projects/#{@project.id}/support", method: :patch do |f| %>

      Enter how much you'd like to support: $<%= f.number_field :funds_acquired %>
      <%= f.submit "Back this project" %>
    <% end %>
  <%else %>
  <br><br>
  <div class="support-this-project?">
    Want to support this project?
    <%= link_to "Log in", "/login"%> or
    <%= link_to "Create an account", "/users/new" %>
    <% end %>
  <% if @project.creator_id == current_user.id %>
    <%= form_for @project, url: "/projects/#{@project.id}", method: :delete do |f| %>
       <div class="delete-project-button"><%= f.submit "Delete Project" %></div>
    <%end%><br><br>
    <%= link_to "Edit Project", edit_project_path %>
  <% end %>
  <br>
  <%= link_to "Main Menu", "/" %>
  </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="form">

  <div class="error">
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  <% end %>
  </div>

  <h1>Edit my profile:</h1>
      <%= form_for @user do |f| %>
        <%= f.label :username %>
        <%= f.text_field :username %> <br>

        <%= f.label :password %>
        <%= f.password_field :password %> <br>

        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %> <br>

        <%= f.label :first_name %>
        <%= f.text_field :first_name %> <br>

        <%= f.label :last_name %>
        <%= f.text_field :last_name %> <br>

        <%= f.label :email %>
        <%= f.text_field :email %> <br>

        <%= f.label :age %>
        <%= f.text_field :age %> <br>

        <%= f.label :gender %>
        <%= f.text_field :gender %> <br>

        <%=f.label :country %>
        <%= f.text_field :country %> <br>

        <%= f.label :occupation %>
        <%= f.text_field :occupation %> <br>

        <%= f.submit %>
      <%end%>

</div>

app/views/users/new.html.erb
<div class="hero-image">
  <div class ="hero-text">
      <div class="form">
        <br><br> <br>
        <h1>Create an account:</h1> <br>
        <div class="error">
        <% if @user.errors.any? %>
          <% @user.errors.full_messages.each do |message| %>
            <p><%= message %></p>
          <% end %>
        <% end %>
        </div>
      <div class="container">
            <%= form_for @user do |f| %>
            <div class="form-group">
              <%= f.label :username %>
              <%= f.text_field :username %>
            </div>
            <div class="form-group">
              <%= f.label :password %>
              <%= f.password_field :password %>
            </div>
            <div class="form-group">
              <%= f.label :password_confirmation %>
              <%= f.password_field :password_confirmation %>
            </div>
            <div class="form-group">
              <%= f.label :first_name %>
              <%= f.text_field :first_name %>
            </div>
            <div class="form-group">
              <%= f.label :last_name %>
              <%= f.text_field :last_name %>
            </div>
            <div class="form-group">
              <%= f.label :email %>
              <%= f.text_field :email %>
            </div>
              <%= f.submit %>
            <%end%>
          </div>
      </div>
    </div>
  </div>

app/views/users/notes.html.erb
<div class="container">
  <img src="https://articulate-heroes.s3.amazonaws.com/uploads/rte/rydofbpq_SpiralNotebook_FirstPage.png" alt="Snow" style="width:100%;">
  <div class="top-left">
    <%= form_for @user, url: "/notes/#{@user.id}", method: "patch" do |f| %>
      <%= f.text_area :note_content, :cols => "97", :rows => "18" %>
      <br>
      <div class="note-button">
        <%= f.submit "Save Notes"%>
            <%end%>
      </div>
      <div class="menu-button">
        <%= link_to "Main Menu", "/" %> <br>
        <%= link_to "Start a project", "/projects/new"%>
      </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="show">

  <h1><%=@user.first_name%> <%= @user.last_name%></h1>
    Username: <%= @user.username %> <br>
    Age: <%= @user.age %> <br>
    Gender: <%= @user.gender %> <br>
    Country: <%= @user.country %> <br>
    Occupation: <%= @user.occupation %> <br>
    <br>
    <% if current_user.id == @user.id %>
      My projects:
    <% else %>
      User's projects:
    <% end %>
      <ul><% @user.created_projects.each do |created_project| %>
      <p><%= link_to created_project.title, project_path(created_project.id) %><br>
          <%= created_project.description[0..100] + "..." %></p>
        <% end %>
      </ul>

      <br>
      <% if current_user.id == @user.id %>
        Backed projects:
      <% else %>
        Projects this user has backed:
      <% end %>
        <ul><% @user.backed_projects.uniq.each do |backed_project| %>
          <p><%= link_to backed_project.title, project_path(backed_project.id) %></p>
        <% end %>
        </ul>

        <br>
        <% if current_user.id == @user.id %>
          <%= link_to "Edit my profile", edit_user_path(@user) %>
         <% end %>
        <br>
        <%= link_to "Main Menu", '/' %>


</div>

app/views/users/stats.html.erb
<div class="stats">
<h1><%=@user.first_name%>'s Statistics</h1>

  Total number of projects: <%=@user.total_projects%> <br>

  Number of projects to reach goal: <%= @user.goal_reached_projects.count%> <br>

  <% @user.goal_reached_projects.each do |project| %>
    <li> <%= link_to project.title, project_path(project) %></li>
  <%end%>

  Total funds acquired: $ <%= @user.total_funds_acquired %> <br>
  Additional funds needed: $
  <%if @user.total_funds_needed - @user.total_funds_acquired < 0 %>
    <%= 0 %>
  <% else %>
   <%= @user.total_funds_needed - @user.total_funds_acquired %>
  <% end %><br>

  Most popular project: <%= link_to @user.most_popular_project.title, project_path(@user.most_popular_project) %> <br>
</div>

app/views/welcome/category.html.erb
<div class="row">
    <div class="search-header col-lg-12">
      <div class="search-by-category">
        <br>Search by category:
        <% @categories.each do |category| %>
          <span><%= link_to category.name, category_path(category.id) %> | </span>
        <% end %>
      </div>
      <br>
    <div class="left-column col-sm-10">
      <div class="card-deck">
        <% @category.projects.each do |project| %>
          <div class="index-info-box col-sm-4">
            <div class="card">
              <div class="card-header">
                <%= project.title %>
              </div>
              <img class="card-img-top" src="<%=project.project_photo%>">
              <div class="card-body">
                <p class="card-text"><%=project.description[0..100] + "..." unless !project.description %></p>
                <a href="/projects/<%=project.id%>" class="btn btn-primary">See Project</a>
              </div>
              <footer>$<%= project.funds_acquired %> pledged of $<%= project.funds_needed %> goal</footer>
            </div>
          </div>
        <% end %>
      </div>
    </div>
</div>

app/views/welcome/home.html.erb
<div class="row">
    <div class="search-header col-lg-12">
      <div class="search-by-category">
        <br>Search by category:
        <% @categories.each do |category| %>
          <span><%= link_to category.name, category_path(category.id) %> | </span>
        <% end %>
      </div>
      <br>
      <div class="search-by-project">
      <%= form_tag("/search", method: :get) do %>
        <%= text_field_tag(:q, "" ,:placeholder => "Search by project") %>
        <%= submit_tag("Search") %>
      <% end %>
      <br>
    </div>
    <div class="left-column col-lg-12">
      <div class="flash">
      <% if flash[:notice] %>
        <%= flash[:notice] %>
      <% end %>
      </div>
      <div class="card-deck">
        <% @projects.each do |project| %>
          <div class="index-info-box col-sm-4">
            <div class="card">
              <div class="card-header">
                <%= project.title %>
              </div>
                <img class="card-img-top" src="<%=project.project_photo%>">
                <div class="card-body">
                  <p class="card-text"><%=project.description[0..100] + "..." unless !project.description %></p>
                  <a href="/projects/<%=project.id%>" class="btn btn-primary">See Project</a>
                </div>
                <footer>$<%= project.funds_acquired %> pledged of $<%= project.funds_needed %> goal</footer>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% if !flash[:notice] %>
  <footer class="app-footer">
    <div class="row col-lg-12">
      <div class="col-sm-4">
        <div class="footer-about">ABOUT</div>
        <div class="footer-about-list">
          <div>Who are we</div>
          <div>Where are we</div>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="footer-support">SUPPORT</div>
        <div class="footer-support-list">
          <div>Give us money</div>
          <div>Please</div>
        </div>
      </div>

      <div class="col-sm-4">
        <div class="footer-careers">CAREERS</div>
        <div class="footer-careers-list">
          <div>Do we look like we have money to hire people?</div>
          <div>Give us money</div>
        </div>
      </div>

    </div>
  </footer>
<% end %>